use pesquisapombal;

insert into tb_pergunta (titulo) values 
("ACADEMIAS"),
("AGÊNCIA BANCÁRIA"),
("ALUGUEL DE ROUPAS"),
("ARMAZÉM DE ESTIVAS E CEREAIS"),
("ARMAZÉM DE RAÇÃO"),
("ARQUITETURA/PROJETOS"),
("ATELIÊ"),
("AUTO PEÇAS"),
("BAR"),
("BOLSAS E CONEXOS"),
("BOMBONIERE"),
("BOUTIQUE"),
("BUFFET"),
("CARTORIO"),
("CASA DE FESTAS"),
("CHURRASCARIA"),
("CLINICA DENTARIA"),
("CLINICAS MEDICAS"),
("CONVENIÊNCIA"),
("COMISSÁRIA DE VEÍCULOS"),
("CONFECÇÕES EM GERAL"),
("CORRESPONDENTE BANCÁRIO"),
("CURSINHO PRÉ-VESTIBULAR "),
("DISTRIBUIDORA DE BEBIDAS"),
("DISTRIBUIDORA DE GÁS"),
("ELETRICISTA"),
("ESCOLAS PARTICULARES"),
("ESCRITORIO ADVOCACIA"),
("ESCRITÓRIO DE CONTABILIDADE"),
("ESTRUTURA, ILUMINAÇÃO E SONORIZAÇÃO"),
("FABRICA DE FARDAMENTOS E CONFECÇÕES"),
("FABRICAÇÃO/CONSERTO DE JÓIAS "),
("FARMÁCIA"),
("FARMACIA VETERINARIA/CLINICA"),
("FISIOTERAPIA / PILATES"),
("FLORICULTURA"),
("FOTO E FILMAGEM"),
("FRIGORIFICO"),
("GRÁFICA/COMUNICAÇÃO VISUAL"),
("HOTEL/POUSADA"),
("LABORATÓRIO ANALISES"),
("LANCHONETE"),
("LOJA DE CALÇADOS"),
("LOJA DE INFORMATICA"),
("LOJA DE MATERIAL DE CONSTRUÇÃO"),
("LOJA DE MOVEIS E ELETROS"),
("LOJA DE PRESENTES E VARIEDADES"),
("MADEREIRA"),
("MARMORARIA"),
("MATERIAL DE IRRIGAÇÃO"),
("MATERIAL ESPORTIVO"),
("MOTO PEÇAS / OFICINA DE MOTOS"),
("OFICINA DE CELULAR"),
("OFICINA MECÂNICA / INJEÇÃO ELETRONICA"),
("OTICAS"),
("PANIFICADORA"),
("PAPELARIA"),
("PASTELARIA"),
("PERFUMARIA"),
("PIZZARIA"),
("PLANO FUNERARIO"),
("POSTO DE COMBUSTIVEIS"),
("PROVEDOR DE INTERNET"),
("RESTAURANTE"),
("SALÃO DE BELEZA (FEMININO)"),
("SALÃO DE ESTETICA"),
("SALÃO/CORTES MASCULINOS"),
("SERRALHARIA"),
("SORVETERIAS"),
("SUPERMERCADO"),
("TECELAGEM"),
("VESTUARIO INFANTIL"),
("VIDRAÇARIA");

insert into tb_alternativa (titulo, id_pergunta) values
("Academia de Leo", 1),
("Fisioforma", 1),
("Flex Forma", 1),
("Forma Corpus", 1),
("Gym Fitnes", 1),
("Podium Academia", 1),
("S3 Fitnes",1 ),
("Outro:", 1),
("Banco Bradesco", 2),
("Banco do Brasil", 2),
("Banco do Nordeste", 2),
("Caixa Economica", 2),
("Sicred", 2),
("Outro:", 2),
("Closet Festas", 3),
("Empório Noivas", 3),
("La Feme Noivas", 3),
("Noivas e Babys", 3),
("Vest Festas", 3),
("Outro:", 3),
("Armazém São José", 4),
("Chico Claro", 4),
("Formiguinha", 4),
("Outro:", 4),
("Adriely", 5),
("Armazém Bandeirante", 5),
("Chico Claro", 5),
("Claustenio", 5),
("JF Casa da Fazenda", 5),
("Outro:", 5),
("Arthur Bandeira", 6),
("Cizia Mouta", 6),
("Projetto (Caroline Queiroga e Daniela)", 6),
("Silvio Sales", 6),
("Outro:", 6),
("Laide Arruda", 7),
("Marlene", 7),
("Solange Rego", 7),
("Outro:", 7),
("Auto Peças Alexandre", 8),
("Auto Peças Martins", 8),
("Auto Peças Queiroga", 8),
("Cascatinha Auto Peças", 8),
("Lider Equipadora", 8),
("Lio Auto Peças", 8),
("Lojas Martins Auto Peças", 8),
("Rojak", 8),
("Outro:", 8),
("Bar Centenario", 9),
("Bar da Galinha", 9),
("Bar Moura", 9),
("Espeto Bar", 9),
("João do Bar", 9),
("Royal Spetos", 9),
("Tô em Casa", 9),
("Outro:", 9),
("Art Baby", 10),
("Art Pura", 10),
("Julia Baby", 10),
("Moleka", 10),
("Ruah", 10),
("Outro:", 10),
("Danielle Caramelos", 11),
("Pirulito's Festas", 11),
("Pombal Caramelos", 11),
("Outro:", 11),
("Aretha Modas", 12),
("D'Classe", 12),
("Dona Morena", 12),
("Elida Modas", 12),
("Freitas For Men", 12),
("Koisas do Corpo", 12),
("Loja Ornamentos (Andrea)", 12),
("Maison T", 12),
("Mistura Fina", 12),
("Moda Viva", 12),
("Pequena Dama", 12),
("Perfil Modas", 12),
("Priscila Boutique", 12),
("Tarcys Sofisticação", 12),
("Outro:", 12),
("Candida Amelia", 13),
("Carminha Fitness", 13),
("Cici Decorações", 13),
("Garden Recepões", 13),
("Outro:", 13),
("1° Cartorio Queiroga", 14),
("2° Cartorio de Oficio", 14),
("Cartorio de Registro", 14),
("Outro:", 14),
("Cici Decorações", 15),
("Pirulito Festas", 15),
("Sonho de Criança", 15),
("Outro:", 15),
("Churrascaria dos Amigos (Barrinha)", 16),
("Churrascaria Maringá", 16),
("Churrascaria Gavel", 16),
("João do Bar", 16),
("Saborear", 16),
("Outro:", 16),
("Clinica Odont.Joana Dark", 17),
("Dr.Arthur Matos", 17),
("Dr.Jayro Wanderley", 17),
("Dr.Marcos Vinícius", 17),
("Dr.Pedro Gomes e Edna", 17),
("Dra.Beatriz", 17),
("Dra.Estefânia e Dr.Wendel", 17),
("Dra.Francimar e Dra.Pratricia", 17),
("Dra.Lenira", 17),
("Dra.Sonia", 17),
("Odonto Primus", 17),
("Sorridente", 17),
("Outro:", 17),
("Cemoan", 18),
("Clinica Bella Vita", 18),
("Clinica D'Posture", 18),
("Clinica da Mulher", 18),
("Santa Cecilla", 18),
("Outro:", 18),
("Conveniência Boa Esperança", 19),
("Conveniência Gavel", 19),
("Conveniência Gomes", 19),
("Conveniência Martins", 19),
("Outro:", 19),
("Alex Pombal", 20),
("Deda Veículos", 20),
("Gavel Veículos", 20),
("GF Veículos", 20),
("CG Car", 20),
("Leomar Veículos", 20),
("Marinho Veículos", 20),
("Outro:", 20),
("Aky Veste", 21),
("Cyda Confecções", 21),
("Donna Bella", 21),
("DZ Modas", 21),
("Giovana Confecções", 21),
("Malharia Nota 10", 21),
("Malharia Simples", 21),
("Martins Confecções", 21),
("Moda Viva", 21),
("Modellina", 21),
("Pallone", 21),
("Rose Confecções", 21),
("Surya", 21),
("Tendencia Confecções", 21),
("Top Modas", 21),
("Vivaz", 21),
("Outro:", 21),
("Bomcopy - Serviços e Emprestimos", 22),
("Casa Loterica", 22),
("CBN Copiadora", 22),
("Enio Ricardo & Negocios", 22),
("PagFácil", 22),
("Pombal Expresso", 22),
("Rede Fácil", 22),
("Outro:", 22),
("Auciele Nobre", 23),
("Minha Vaga", 23),
("Pró Enem (Arco Iris", 23),
("Outro:", 23),
("Adega da Bebida", 24),
("Armazem São José", 24),
("Barrinha", 24),
("Maroquinhas", 24),
("Misturama", 24),
("Multi Bebidas", 24),
("Nezinho Bebidas", 24),
("Pombal Bebidas", 24),
("Sales Bebidas", 24),
("To Kum Sede", 24),
("Outro:", 24),
("Alencar Gás", 25),
("Brasil Gás", 25),
("Copagaz", 25),
("Novo Gás", 25),
("Outro:", 25),
("André", 26),
("Babaloo", 26),
("Jó Eletricista", 26),
("Moacir", 26),
("Nenem", 26),
("Serginho", 26),
("Tales", 26),
("Outro:", 26),
("CMJ Escola Menino Jesus", 27),
("Escola Arco Iris", 27),
("Escola JHD", 27),
("Principio do Saber", 27),
("Roberta Fernandes", 27),
("Outro:", 27),
("Adimilsom Leite e Maria do Carmo Dantas", 28),
("Alberg Bandeira (Beto Calado)", 28),
("Antonio Cezar L.Ugulino", 28),
("Aristoteles e Sefra Poliana", 28),
("Gustavo Nunes", 28),
("Jackson Costa Ribeiro", 28),
("Jaques Wanderley e Mayara", 28),
("Queiroga", 28),
("Jorge Henrique", 28),
("Marques e Sousa", 28),
("Quezia e Thiago", 28),
("Raniel Wanderley e Mayara Roagna", 28),
("Robson Brito", 28),
("Santos e Nogueira", 28),
("Segundo", 28),
("Thyago Carneiro", 28),
("Outro:", 28),
("Astec (Jota)", 29),
("Claro Contabilidade", 29),
("Dodó", 29),
("Elenita Contabilidade", 29),
("Eliete Contabilidade", 29),
("Evolução Contábel", 29),
("Excellent Contabilidade", 29),
("Gilmarcos", 29),
("Italo Marques", 29),
("Moacir", 29),
("RG Contabilidade", 29),
("Sefec (Andrea)", 29),
("Sefef", 29),
("Socorro", 29),
("Tales Contabilidade", 29),
("Outro:", 29),
("JM Som", 30),
("NS Eventos (Wyllender", 30),
("Pena Sonorização", 30),
("Rainner Galdino", 30),
("Outro:", 30),
("Moleka", 31),
("Polo e CIA", 31),
("Tendência Confecções", 31),
("Kurumin", 31),
("Vandinha Moda Praia", 31),
("Outro:", 31),
("Aky Jóias", 32),
("Jóia Rara", 32),
("Nova Jóia", 32),
("Pingo de Ouro", 32),
("Outro:", 32),
("Biofarma", 33),
("Droga Center", 33),
("Farma Dantas", 33),
("Farma Formula", 33),
("Farma Olivia", 33),
("Farmacia do Povo", 33),
("Farmacia do Trabalhador", 33),
("Farmacia dos Pobres", 33),
("Farmacia Moderna", 33),
("Farmacia Nova", 33),
("Farmacia Pro Saúde", 33),
("Farmacia Queiroga", 33),
("Farmacia Santa Cecilia", 33),
("Pharma Vida", 33),
("Outro:", 33),
("Agroveter União", 34),
("Cães e Gatos", 34),
("Claravet", 34),
("Pet Shop Saúde Animal", 34),
("Valmir Veterinario", 34),
("Vetercenter", 34),
("Outro:", 34),
("D'Posture", 35),
("Fisio Forma", 35),
("Fisioniiw", 35),
("Revitalize", 35),
("Studio Pilates", 35),
("Outro:", 35),
("Aninha Flores", 36),
("Rosa Morena", 36),
("Outro:", 36),
("Almeida Foto", 37),
("Foto em Foco", 37),
("Foto Ideal", 37),
("Moaby Paixão", 37),
("Outro:", 37),
("Boi de Ouro", 38),
("Carnes e Frio", 38),
("Central das Carnes", 38),
("Frigoboi", 38),
("Frigorifico Boi Forte", 38),
("Frigorifico Bom Jesus", 38),
("Frigorifico Maringá", 38),
("Frigotil", 38),
("Marconildo (Carnes e CIA)", 38),
("O Esquinão", 38),
("Shopping das Carnes", 38),
("Outro:", 38),
("Copiadora Colibri", 39),
("Design Gráfica", 39),
("Fred Artes", 39),
("Gráfica Andyara", 39),
("Gráfica Ciromar", 39),
("Gráfica Dias", 39),
("Gráfica do Estudante", 39),
("Ney Gráfica", 39),
("Vinicius Gráfica", 39),
("Outro:", 39),
("Hotel Rio Verde", 40),
("Pousada Mandacaru", 40),
("Pousada Nordeste", 40),
("Pousada Paraíso", 40),
("Pousada Shalom", 40),
("Pousada Sonho Azul", 40),
("Outro:", 40),
("Analises (Dra.Ligia)", 41),
("Dra.Marta", 41),
("Dra.Salete", 41),
("Lab Vas", 41),
("Santa Cecilia", 41),
("Outro:", 41),
("Big Mix", 42),
("Cotidiano (Rosario)", 42),
("Deu Fome", 42),
("Divino Pão de Queijo", 42),
("Doce Encontro", 42),
("Doce Fatia", 42),
("Fofoquinha", 42),
("Gilson Lanches", 42),
("Mais que Delicia", 42),
("Mariu's", 42),
("MD Lanches", 42),
("NE Lanches", 42),
("O Encontro", 42),
("Planeta Lanches", 42),
("Ponto Mix", 42),
("Rei dos Salgados", 42),
("Rota Burger", 42),
("Sabor do Sertão", 42),
("Outro:", 42),
("A Moderna Calçados", 43),
("A Vencedora Calçados", 43),
("BK Calçados", 43),
("Calce Bem (Socorro de Jesus) ", 43),
("Exótica Calçados", 43),
("Marcos Calçados", 43),
("Passo a Passo Calçados", 43),
("Tendência Calçados", 43),
("Outro:", 43),
("Central TEC", 44),
("Connect", 44),
("Digitus", 44),
("Grupo Barbosa", 44),
("Outro:", 44),
("Adeplam Engenharia", 45),
("Agroveter Construções", 45),
("Armazem Alvorada", 45),
("Casa do Construtor", 45),
("Casa do Norte", 45),
("Cesario Construções", 45),
("DW Construções", 45),
("Elton Construções", 45),
("Grupo Barbosa", 45),
("Lojão da Ceramica", 45),
("Lojas Martins", 45),
("Outro:", 45),
("Armazem Paraíba", 46),
("Eletrolar", 46),
("Lojão Rio do Peixe", 46),
("Lojas Lacerda", 46),
("Magazine Luiza", 46),
("Outro:", 46),
("Aninha Flores", 47),
("Carlitu's Variedade", 47),
("Casa Bandeira", 47),
("Casa Bordarema", 47),
("Lojas Martins", 47),
("Maringá Shopping", 47),
("Polyana Presentes", 47),
("Rei dos Presentes", 47),
("Sefora Presentes", 47),
("Tem de tudos", 47),
("Varejão dos Importados", 47),
("Outro:", 47),
("Madereira Bezerra", 48),
("Madereira Lobão", 48),
("Madereia Monteiro", 48),
("Madereira NªSra. Aparecida", 48),
("Outro:", 48),
("Gran Pombal", 49),
("Nossa Senhora do Rosário", 49),
("Ponto Certo", 49),
("Outro:", 49),
("Armazem Oliveira", 50),
("Bandeira Irrigação", 50),
("Casa Almeida", 50),
("Outro:", 50),
("Marcos Calçados", 51),
("Modellina Sports", 51),
("O Mundo dos Esportes", 51),
("Passo a Passo Sports", 51),
("Sport Modas", 51),
("Varejão dos Sports", 51),
("Outro:", 51),
("Central Motos", 52),
("Danilo Peças", 52),
("Estilo Motos", 52),
("Moto Serve", 52),
("MS Motos", 52),
("Pau Brasil Motos (Honda)", 52),
("Sertão Motos", 52),
("Universo Duas Motos", 52),
("Outro:", 52),
("Alô Cell", 53),
("Dantas Cell", 53),
("Eletrosystem", 53),
("Oficina do Celular", 53),
("Pombal Cell", 53),
("Outro:", 53),
("Azuil Car", 54),
("Oficina Martins", 54),
("Santos Automotivos", 54),
("Stop Car", 54),
("Outro:", 54),
("A Graciosa", 55),
("Otica Bela Visão", 55),
("Otica D'Lucas", 55),
("Otica Dinz", 55),
("Otica Medeiros", 55),
("Otica Onias", 55),
("Otica Mirna", 55),
("Outro:", 55),
("Delicias do Trigo", 56),
("Dois Irmãos", 56),
("Mão na Massa (Cemar)", 56),
("Padaria da Galega", 56),
("Padaria da Neta", 56),
("Panificadora Bom Jesus", 56),
("Panificadora Bom Sucesso", 56),
("Panificadora Delicias do Trigo", 56),
("Panificadora Ouro Branco", 56),
("Panificadora União", 56),
("Pão Nosso", 56),
("Paulistana", 56),
("Primu's", 56),
("Outro:", 56),
("Colibri", 57),
("Gráfica do Estudante", 57),
("Papelaria Andyara", 57),
("Papelaria Help", 57),
("Papelaria Martins", 57),
("Outro:", 57),
("Casarão do Pastel", 58),
("Fofocas Salgados", 58),
("Pastelânia", 58),
("Pastelaria Alencar", 58),
("Outro:", 58),
("Atuality Parfum", 59),
("Matheus Importados", 59),
("Natura", 59),
("O Boticario", 59),
("Outro:", 59),
("D'Italia", 60),
("Nordestina", 60),
("Pizzarela (Marquinhos)", 60),
("Pizzaria Paulistana", 60),
("Outro:", 60),
("Asfran", 61),
("Digna", 61),
("PAF", 61),
("Santa Paz", 61),
("Zezinho", 61),
("Outro:", 61),
("Posto Boa Esperança", 62),
("Posto BR Maravilha LTDA", 62),
("Posto Gavel", 62),
("Posto Maringá", 62),
("Posto Martins", 62),
("Outro:", 62),
("Brisanet", 63),
("M.Tec", 63),
("Torpedo Link", 63),
("WR Link", 63),
("Outro:", 63),
("Altas Horas", 64),
("Contemporaneo", 64),
("Marius Restaurante", 64),
("Saborear", 64),
("Waynos", 64),
("Outro:", 64),
("Aldeny Cabelereira", 65),
("Aline Gabriele", 65),
("Belezaria La Belle", 65),
("Delyene", 65),
("Diana Salão", 65),
("Grabiela Moura", 65),
("Lurdinha Cabelereira", 65),
("Luz e Cor", 65),
("Preguinho", 65),
("Rayane Cabelereira", 65),
("Salão Cabelos Fashion", 65),
("Salão Charme e Beleza", 65),
("Salão Novo Visual", 65),
("Sildenira Cabelereira", 65),
("Solane Rego", 65),
("Solange Cabelereira", 65),
("Studio Hair Segundo Urtiga", 65),
("Tauã Elias", 65),
("Outro:", 65),
("Adriana Depilação", 66),
("Aninha Estetica e Beleza", 66),
("Bella Depil", 66),
("Fernanda Filha de seu Biu", 66),
("Mara Depilação", 66),
("Salão Cabelos Fashion (Mara)", 66),
("Viviane Studio Beleza", 66),
("Outro:", 66),
("Chagas", 67),
("Porfírio", 67),
("Salão Cabelos Fashion", 67),
("Studio Hair Segunda Urtiga", 67),
("Tauã Elias", 67),
("Outro:", 67),
("Casa dos Ferros", 68),
("Paulo Serralheria", 68),
("Pretonio Serralharia", 68),
("Serralharia ", 68),
("Serralharia STª Rosa", 68),
("Serralharia Valmarques", 68),
("ZF Serralharia", 68),
("Outro:", 68),
("Era do Gelo", 69),
("Expresso", 69),
("Flor de Lis", 69),
("Milk Shake Mix", 69),
("Point Mix", 69),
("Outro:", 69),
("Alipio Supermercado", 70),
("Center Box", 70),
("Mercadinho Cici", 70),
("Mercadinho do Pelé", 70),
("Mercadinho Marçal", 70),
("Mercadinho Oliveira", 70),
("Mercadinho Real", 70),
("Mercadinho Trigueiro", 70),
("Mercadinho Viturino", 70),
("Ponto Forte", 70),
("Supermercado Alencar", 70),
("Supermercado Compre Mais", 70),
("Supermercado Sertanejo e Economico", 70),
("Supermercado Vaz", 70),
("Supermercado Maia I, II e III", 70),
("Varejão Bom Preço", 70),
("Varejão Maringá", 70),
("Outro:", 70),
("Nossa Casa", 71),
("União Textil", 71),
("Outro:", 71),
("Baby Kids", 72),
("Bia Baby", 72),
("Koisas do Corpo", 72),
("Lacerda Baby", 72),
("Meloka", 72),
("Pequena Dama", 72),
("Pimpolhos", 72),
("Solange Enxovais", 72),
("Outro:", 72),
("J A Vidros", 73),
("Pombal Vidros", 73),
("Vidraçarias Almeida", 73),
("Vidro e CIA", 73),
("Outro:", 73);
















